# Generated by Django 3.2 on 2021-04-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
