# Generated by Django 3.2 on 2021-04-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210421_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='feelings',
            field=models.ManyToManyField(to='main_app.Feelings'),
        ),
    ]
